### ISSUE TITLE
Ошибка лампочек

### ISSUE THREAD

**Issue by wannaliveinpeace** [TeoDar/stalcraft_signals#11]
Скачал, все настроил под моник, координаты указал, поменял кол-во лампочек, но словил вот это: 
Ожидаю до 8 лампочки...
Traceback (most recent call last):
  File "signal_catcher.py", line 33, in catch
  File "signal_catcher.py", line 76, in searching
  File "signal_catcher.py", line 105, in burn_signal
TypeError: '<=' not supported between instances of 'int' and 'str'

**Comment by wannaliveinpeace** [comment]
А, да, и если есть возможность, то хотелось бы чуть подправить кол-во лампочек, примерно на 5 с половиной лампочке(после третьего проигрывания звука поиска) уже можно его отключать, и сигнал все равно найдется, смысла до 8 лампы ждать нет, сигнал утащат быстрее
